[project]
name = "rust_jax_ffi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax>=0.6.2",
    "nanobind>=2.7.0",
]
